#!/bin/bash

# TARGET_DIR="gen"
# TARGET_DIR="ultimate"
# TARGET_DIR="sync_table"
TARGET_DIR="gormgen"

PROJECT_DIR=$(dirname "$0")
GENERATE_DIR="$PROJECT_DIR/cmd/$TARGET_DIR"

AUTOGENERATED_FILES_DIR="pkg/generated/financial_integration_service_api/v1/clickhouse_financial_service.pb.gorm.go"

cd "$GENERATE_DIR" || exit

echo "Start Generating"
go run .

pwd
cd ../../
pwd

grep -rl 'gorm:"type:text\[\]"' "$AUTOGENERATED_FILES_DIR" 

# we changet text[] to Array(string) in clickhouse.pb.gorm.go because clickhouse
# does not support text[] type in table definition
sed -i '' 's/text\[\]/Array(String)/g' pkg/generated/financial_integration_service_api/v1/clickhouse_financial_service.pb.gorm.go            