name: Golang Release

defaults:
 run:
  working-directory: .

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
            go-version: 1.21
      - run: go test -v ./...
  # pr-checks-build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - uses: go-semantic-release/action@v1
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         changelog-file: CHANGELOG.md
  #         update-file: pkg/version/version.go